# Generated by Django 4.2 on 2025-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_material_content_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
